name: Build and run tests
run-name: ${{ github.actor }} builds and tests the change
on:
  pull_request
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sqglobe/match-search-ubuntu-noble
      credentials:
       username: ${{ github.actor }}
       password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Build project
        run: |
          mkdir -p build
          cd build
          cmake -G Ninja ..
          cmake --build .
      - name: Change owner
        run: chown -R ubuntu:ubuntu  build/*
      - name: Run tests
        run: |
          cd build
          QT_QPA_PLATFORM=offscreen su -c "ctest -j --output-on-failure" ubuntu
      - name: Save artifacts
        run: |
          cd build 
          mkdir artifacts
          cmake --install . --prefix artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: match-search-${{ github.sha }}
          path: build/artifacts/*
